apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-producer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-producer
    spec:
      containers:
      - name: producer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Use values from values.yaml
        env:
          - name: RABBITMQ_HOST
            value: "my-rabbitmq"
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Release.Name }}-producer
