apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: itaef/flask-app:1.0.0.F
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: REDIS_HOST
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: my-project
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask
