apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "flask-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: {{ include "flask-app.name" . }}
