apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: multi-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          resources:
            requests:
              memory: "32Mi"   # specify the memory request
              cpu: "125m"      # specify the CPU request
            limits:
              memory: "64Mi"  # specify the memory limit
              cpu: "250m"      # specify the CPU limit
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-volume
              mountPath: /etc/redis
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: redis-config

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: multi-tier-app
spec:
  selector:
    app: redis
  ports:
    - port: 6379
