apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:latest
          resources:
            requests:
              memory: "32Mi"   # specify the memory request
              cpu: "125m"      # specify the CPU request
            limits:
              memory: "64Mi"  # specify the memory limit
              cpu: "250m"      # specify the CPU limit
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: database-name
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-backend-service
  namespace: fullstack-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend
