apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fullstack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          resources:
            requests:
              memory: "32Mi"   # specify the memory request
              cpu: "125m"      # specify the CPU request
            limits:
              memory: "64Mi"  # specify the memory limit
              cpu: "250m"      # specify the CPU limit
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: "backend-service"
            - name: BACKEND_PORT
              value: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: my-sql-frontend-service
  namespace: fullstack-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: frontend
