apiVersion: v1
kind: ResourceQuota
metadata:
  name: fullstack-app-quota
  namespace: fullstack-app
spec:
  hard:
    requests.cpu: "4"          # Set maximum CPU requests to 4 cores
    requests.memory: 4Gi       # Set maximum memory requests to 4GiB
    limits.cpu: "4"            # Set maximum CPU limits to 8 cores
    limits.memory: 4Gi         # Set maximum memory limits to 8GiB
    pods: "20"                 # Set maximum number of pods to 20
